services:
  minilims:
    image: minilims-nginx
    container_name: minilims
    hostname: minilims
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /etc/letsencrypt/live/parf-lims-mini.data-srv.fyi:/etc/letsencrypt/live/parf-lims-mini.data-srv.fyi:ro
      - /etc/letsencrypt/archive/parf-lims-mini.data-srv.fyi:/etc/letsencrypt/archive/parf-lims-mini.data-srv.fyi:ro
      - ./minilims.html:/usr/share/nginx/html/index.html:ro
    networks:
      - minilims_network

networks:
  minilims_network:
    driver: bridge

